# Generated by Django 6.0.4 on 2026-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Forcé à la première connexion après création ou reset par un superuser.",
                verbose_name="Doit changer son mot de passe",
            ),
        ),
    ]
