# Generated by Django 6.0.4 on 2026-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_reviewer",
            field=models.BooleanField(
                default=False,
                help_text="Compte à accès limité — peut uniquement déposer ses relectures.",
                verbose_name="Relecteur·ice",
            ),
        ),
    ]
