# Generated by Django 6.0.4 on 2026-04-23 05:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Adresse e-mail"
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Affiliation"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Spécialités, compétences, contexte de collaboration…",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "usual_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("author", "Auteur·ice"),
                                ("internal_reviewer", "Relecteur·ice interne"),
                                ("external_reviewer", "Relecteur·ice externe"),
                            ],
                            max_length=50,
                        ),
                        blank=True,
                        default=list,
                        verbose_name="Rôles habituels",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="journals.journal",
                        verbose_name="Revue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
