# Generated by Django 6.0.4 on 2026-04-23 05:25

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Titre")),
                (
                    "author_name_override",
                    models.CharField(
                        blank=True,
                        help_text="Laissez vide pour utiliser le nom du contact.",
                        max_length=200,
                        verbose_name="Nom affiché (forçage)",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("introduction", "Introduction"),
                            ("summary", "Résumé"),
                            ("review", "Recension"),
                            ("interview", "Entretien"),
                            ("other", "Autre"),
                        ],
                        default="article",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre dans le numéro"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("received", "Reçu"),
                            ("in_review", "En relecture"),
                            ("reviews_received", "Relectures reçues"),
                            ("in_author_revision", "En révision auteur"),
                            ("revised", "Révisé"),
                            ("validated", "Validé"),
                        ],
                        default="received",
                        max_length=50,
                        protected=True,
                        verbose_name="État",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_articles",
                        to="contacts.contact",
                        verbose_name="Auteur·ice",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="issues.issue",
                        verbose_name="Numéro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="InternalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=False,
                        help_text="Cochée si générée par le système (changement d'état, de titre, etc.).",
                        verbose_name="Note automatique",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_notes",
                        to="articles.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur·ice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note interne",
                "verbose_name_plural": "Notes internes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Numéro de version"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="articles/versions/", verbose_name="Fichier"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="articles.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Déposé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version d'article",
                "verbose_name_plural": "Versions d'article",
                "ordering": ["version_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "version_number"),
                        name="unique_article_version",
                    )
                ],
            },
        ),
    ]
