# Generated by Django 6.0.4 on 2026-04-23 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="internalnote",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_notes",
                to="issues.issue",
                verbose_name="Numéro",
            ),
        ),
        migrations.AlterField(
            model_name="internalnote",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_notes",
                to="articles.article",
                verbose_name="Article",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("article__isnull", False), ("issue__isnull", True)),
                    models.Q(("article__isnull", True), ("issue__isnull", False)),
                    _connector="OR",
                ),
                name="internalnote_article_xor_issue",
            ),
        ),
    ]
