# Generated by Django 6.0.4 on 2026-04-23 22:15

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_internalnote_add_issue_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleversion",
            name="file",
            field=models.FileField(
                upload_to=apps.core.storage.VersionedUploadTo("articles/versions"),
                verbose_name="Fichier",
            ),
        ),
    ]
