# Generated by Django 6.0.4 on 2026-04-25 13:22

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_versioned_upload_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "En attente"),
                    ("received", "Reçu"),
                    ("in_review", "En relecture"),
                    ("reviews_received", "Relectures reçues"),
                    ("in_author_revision", "En révision auteur"),
                    ("revised", "Révisé"),
                    ("validated", "Validé"),
                ],
                default="pending",
                max_length=50,
                protected=True,
                verbose_name="État",
            ),
        ),
    ]
