# Generated by Django 6.0.4 on 2026-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_add_pending_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="abstract",
            field=models.TextField(blank=True, verbose_name="Résumé"),
        ),
    ]
