# Generated by Django 6.0.4 on 2026-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_articleversion_uploaded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="blind_review",
            field=models.BooleanField(
                default=False, verbose_name="Relecture à l'aveugle"
            ),
        ),
    ]
