# Generated by Django 6.0.4 on 2026-06-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_blind_review_and_anonymous_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="blind_review",
        ),
    ]
