# Generated by Django 6.0.4 on 2026-06-06 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_blind_review_on_issue"),
        ("issues", "0009_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="issues.section",
                verbose_name="Section",
            ),
        ),
    ]
