# Generated by Django 6.0.4 on 2026-04-23 05:25

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Ex : « 14 » ou « 14-15 » pour un double numéro.",
                        max_length=20,
                        verbose_name="Numéro",
                    ),
                ),
                (
                    "thematic_title",
                    models.CharField(max_length=300, verbose_name="Titre thématique"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "editor_name",
                    models.CharField(
                        help_text="Champ texte libre — souvent une personne extérieure au comité.",
                        max_length=200,
                        verbose_name="Responsable éditorial·e",
                    ),
                ),
                (
                    "planned_publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de parution prévue"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="issues/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "final_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="issues/final_pdfs/",
                        verbose_name="PDF final",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("under_review", "En évaluation"),
                            ("accepted", "Accepté"),
                            ("in_production", "En production"),
                            ("sent_to_publisher", "Envoyé à l'éditeur"),
                            ("published", "Publié"),
                            ("refused", "Refusé"),
                        ],
                        default="under_review",
                        max_length=50,
                        protected=True,
                        verbose_name="État",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="journals.journal",
                        verbose_name="Revue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numéro",
                "verbose_name_plural": "Numéros",
                "ordering": ["-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("journal", "number"), name="unique_issue_number"
                    )
                ],
            },
        ),
    ]
