# Generated by Django 6.0.4 on 2026-04-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_issuedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de publication"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="refused_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de refus"
            ),
        ),
    ]
