# Generated by Django 6.0.4 on 2026-05-19 09:47

from django.db import migrations, models


def populate_sort_order(apps, schema_editor):
    Issue = apps.get_model("issues", "Issue")
    for issue in Issue.objects.filter(sort_order__isnull=True):
        try:
            issue.sort_order = int(issue.number.split("-")[0].strip())
            issue.save(update_fields=["sort_order"])
        except (ValueError, AttributeError):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_remove_unique_issue_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("sort_order"), descending=True, nulls_last=True
                    )
                ],
                "verbose_name": "Numéro",
                "verbose_name_plural": "Numéros",
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="sort_order",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Entier utilisé pour trier les numéros. Auto-calculé depuis le numéro ; à corriger manuellement pour les doubles numéros si nécessaire.",
                null=True,
                verbose_name="Ordre de tri",
            ),
        ),
        migrations.RunPython(populate_sort_order, migrations.RunPython.noop),
    ]
