# Generated by Django 6.0.4 on 2026-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0007_issue_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="blind_review",
            field=models.BooleanField(
                default=False, verbose_name="Relecture à l'aveugle"
            ),
        ),
    ]
