# Generated by Django 6.0.4 on 2026-04-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0002_journal_accent_palette"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="directors",
            field=models.CharField(
                blank=True,
                help_text="Noms des directeurs/directrices, séparés par des virgules.",
                max_length=500,
                verbose_name="Direction de la revue",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="founded_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Année de fondation"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="issn_online",
            field=models.CharField(
                blank=True,
                help_text="Format : XXXX-XXXX",
                max_length=9,
                verbose_name="ISSN en ligne",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="issn_print",
            field=models.CharField(
                blank=True,
                help_text="Format : XXXX-XXXX",
                max_length=9,
                verbose_name="ISSN papier",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="periodicity",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Périodicité"
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="publisher",
            field=models.CharField(blank=True, max_length=200, verbose_name="Éditeur"),
        ),
        migrations.AddField(
            model_name="journal",
            name="website",
            field=models.URLField(blank=True, max_length=300, verbose_name="Site web"),
        ),
    ]
