# Generated by Django 6.0.4 on 2026-04-25 19:24

import apps.journals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0003_journal_institutional_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du document"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optionnel — pour préciser le contenu du document.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.journals.models._journal_doc_upload_to,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="journals.journal",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ajouté par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de la revue",
                "verbose_name_plural": "Documents de la revue",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
