# Generated by Django 6.0.4 on 2026-05-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0005_alter_journaldocument_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="email_intro",
            field=models.TextField(
                blank=True,
                help_text="Paragraphe personnalisé inséré en tête de chaque email envoyé aux relecteurs.",
                verbose_name="Introduction email",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="email_sender_name",
            field=models.CharField(
                blank=True,
                help_text="Affiché dans le champ « De : » des emails. Si vide, le nom de la revue est utilisé.",
                max_length=200,
                verbose_name="Nom d'expéditeur email",
            ),
        ),
    ]
