# Generated by Django 6.0.4 on 2026-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0006_journal_email_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="auto_reminder_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Si renseigné, un rappel est envoyé automatiquement X jours avant la deadline. Laisser vide pour désactiver.",
                null=True,
                verbose_name="Rappel automatique (jours avant deadline)",
            ),
        ),
    ]
