# Generated by Django 6.0.4 on 2026-07-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0007_journal_reminder_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="kind",
            field=models.CharField(
                choices=[
                    ("periodical", "Revue périodique"),
                    ("standalone", "Projet ponctuel"),
                ],
                default="periodical",
                help_text="Revue à numéros multiples, ou projet ponctuel (livre, actes).",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
