# Generated by Django 6.0.4 on 2026-04-23 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "reviewer_name_snapshot",
                    models.CharField(
                        max_length=200, verbose_name="Nom du relecteur·ice (snapshot)"
                    ),
                ),
                ("deadline", models.DateField(verbose_name="Date limite")),
                (
                    "state",
                    models.CharField(
                        choices=[("expected", "Attendue"), ("received", "Reçue")],
                        default="expected",
                        max_length=20,
                        verbose_name="État",
                    ),
                ),
                (
                    "received_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reviews/files/",
                        verbose_name="Fichier de relecture",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reçue le"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("favorable", "Favorable"),
                            ("needs_revision", "Révision requise"),
                            ("unfavorable", "Défavorable"),
                        ],
                        max_length=20,
                        verbose_name="Verdict",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Notes internes"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="articles.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "article_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="articles.articleversion",
                        verbose_name="Version relue",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.contact",
                        verbose_name="Relecteur·ice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de relecture",
                "verbose_name_plural": "Demandes de relecture",
                "ordering": ["deadline"],
            },
        ),
    ]
