# Generated by Django 6.0.4 on 2026-04-23 22:15

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrequest",
            name="received_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.VersionedUploadTo("reviews/files"),
                verbose_name="Fichier de relecture",
            ),
        ),
    ]
