# Generated by Django 6.0.4 on 2026-04-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_versioned_upload_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrequest",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Envoyée le"
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("assigned", "Désignée"),
                    ("sent", "Envoyée"),
                    ("received", "Reçue"),
                    ("declined", "Refusée"),
                ],
                default="assigned",
                max_length=20,
                verbose_name="État",
            ),
        ),
    ]
