# Generated by Django 6.0.4 on 2026-05-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_reviewer_role_and_contact_link"),
        ("reviews", "0004_reviewrequest_migrate_expected_to_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrequest",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Rappel envoyé le"
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contacts.contact",
                verbose_name="Relecteur·ice",
            ),
        ),
    ]
