# Generated by Django 6.0.4 on 2026-06-05 19:03

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrequest",
            name="anonymous_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.core.storage.VersionedUploadTo("reviews/anonymous"),
                verbose_name="Fichier anonymisé",
            ),
        ),
    ]
